[package]
name = "kamiya"
description = "An easy, fast and lightweight tool to create notes in terminal."
version = "0.4.0"
edition = "2021"

[dependencies]
clap = "4.2.4"
home = "0.5.4"
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
wl-clipboard-rs = "0.7.0"
