[package]
name = "kamiya"
description = "Note storage directly in the terminal."
version = "0.3.0-dev"
edition = "2021"

[dependencies]
clap = "4.2.4"
home = "0.5.4"
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
