[package]
name = "kami"
description = "Storage space for your notes - directly in the terminal."
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.2.4"
home = "0.5.4"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
