[package]
name = "kamiya_config"
description = "Library for interaction with Kamiya configuration."
readme = "../README.md"
license = "GPL-3.0"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
